server:
  port: 8000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.url:http://localhost:8761/eureka}

spring:
  application:
    name: ca-gateway
  cloud:
    gateway:
      routes:
        - id: ca-user
          uri: lb://CA-USER
          predicates:
            - Path=/ca-user/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: ca-product
          uri: lb://CA-PRODUCT
          predicates:
            - Path=/ca-product/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
        - id: ca-reservation
          uri: lb://CA-RESERVATION
          predicates:
            - Path=/ca-reservation/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
