server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.url:http://localhost:8761/eureka}

spring:
  application:
    name: ca-gateway
  cloud:
    gateway:
      routes:
        - id: ca-user
          uri: lb://CA-USER
          predicates:
            - Path=/ca-user/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ca-user/(?<segment>.*), /$\{segment}
        - id: ca-product
          uri: lb://CA-PRODUCT
          predicates:
            - Path=/ca-product/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ca-product/(?<segment>.*), /$\{segment}
        - id: ca-reservation
          uri: lb://CA-RESERVATION
          predicates:
            - Path=/ca-reservation/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ca-reservation/(?<segment>.*), /$\{segment}
